### PR TITLE
fixes #71, fixes #73, move tests underneath

### LINKED ISSUE #71: Add gitattributes file to ignore ipynb

### LINKED ISSUE #73: Remove lint ignore
https://github.com/timkpaine/jupyterlab_celltests/blob/master/setup.cfg#L9

### PR DESCRIPTION
**Pull request by timkpaine**

### CODE REVIEW

**Comment by ceball** [comment]
Makes sense to move the tests into the package. (Assume you'll be updating the Makefile too if you haven't already done it by the time I finish this sentence.)

Are you using an auto-formatter? If so, can you add it to the project requirements, and I'll use it too. (And you'll be able to remove my recent `flake8 --ignore=E201,E241 tests` hack from the Makefile too, in case you didn't notice that one yet.)

**Comment by timkpaine** [comment]
`make fix`

If you just type `make` in any of my repos it will tell you what you can do

**Comment by ceball** [comment]
Ah, thanks. I used to use make a lot, then got out of the habit over the last few years (as there's often no Makefile in many projects these days :( ).

> If you just type make in any of my repos it will tell you what you can do

Not if I don't respect that and fail to add docs for new targets, it won't ;)

**Comment by ceball** [comment]
> Not if I don't respect that and fail to add docs for new targets

fixed in #75

**Pull request merged**
